#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.2.1 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Thu Jan 19 14:17:43 JST 2023
# SW Build 3414424 on Sun Dec 19 10:57:14 MST 2021
#
# IP Build 3405791 on Sun Dec 19 15:54:35 MST 2021
#
# usage: compile.sh
#
# ****************************************************************************
set -Eeuo pipefail
# compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -prj pattern_tb3_vlog.prj"
xvlog --incr --relax -prj pattern_tb3_vlog.prj 2>&1 | tee compile.log

# compile VHDL design sources
echo "xvhdl --incr --relax -prj pattern_tb3_vhdl.prj"
xvhdl --incr --relax -prj pattern_tb3_vhdl.prj 2>&1 | tee -a compile.log

echo "Waiting for jobs to finish..."
echo "No pending jobs, compilation finished."
