#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.2.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Jan 13 02:19:48 JST 2023
# SW Build 3414424 on Sun Dec 19 10:57:14 MST 2021
#
# IP Build 3405791 on Sun Dec 19 15:54:35 MST 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot pattern_tb2_behav xil_defaultlib.pattern_tb2 xil_defaultlib.glbl -log elaborate.log"
xelab --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot pattern_tb2_behav xil_defaultlib.pattern_tb2 xil_defaultlib.glbl -log elaborate.log

