#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.2.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Jan 13 02:19:50 JST 2023
# SW Build 3414424 on Sun Dec 19 10:57:14 MST 2021
#
# IP Build 3405791 on Sun Dec 19 15:54:35 MST 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim pattern_tb2_behav -key {Behavioral:sim_2:Functional:pattern_tb2} -tclbatch pattern_tb2.tcl -log simulate.log"
xsim pattern_tb2_behav -key {Behavioral:sim_2:Functional:pattern_tb2} -tclbatch pattern_tb2.tcl -log simulate.log

