# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pattern.xdc

# IP: ip/rgb2dvi_0/rgb2dvi_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rgb2dvi_0 || ORIG_REF_NAME==rgb2dvi_0} -quiet] -quiet

# IP: ip/pckgen/pckgen.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pckgen || ORIG_REF_NAME==pckgen} -quiet] -quiet

# XDC: ip/rgb2dvi_0/src/rgb2dvi.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==rgb2dvi_0 || ORIG_REF_NAME==rgb2dvi_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: ip/rgb2dvi_0/src/rgb2dvi_ooc.xdc

# XDC: ip/rgb2dvi_0/src/rgb2dvi_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==rgb2dvi_0 || ORIG_REF_NAME==rgb2dvi_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/soshi/workspace/vivado_tutorial/pattern/pattern.gen/sources_1/ip/pckgen/pckgen_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==pckgen || ORIG_REF_NAME==pckgen} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/soshi/workspace/vivado_tutorial/pattern/pattern.gen/sources_1/ip/pckgen/pckgen.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==pckgen || ORIG_REF_NAME==pckgen} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/soshi/workspace/vivado_tutorial/pattern/pattern.gen/sources_1/ip/pckgen/pckgen_ooc.xdc
